"""events and more

Revision ID: 7025bcd668e3
Revises: 28506d769e15
Create Date: 2026-02-08 21:45:05.487877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7025bcd668e3'
down_revision: Union[str, Sequence[str], None] = '28506d769e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photos', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'event_id')
    # ### end Alembic commands ###
