"""Add collections

Revision ID: ecaed219ad1f
Revises: fa8b6af0774b
Create Date: 2026-02-11 15:03:13.320124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecaed219ad1f'
down_revision: Union[str, Sequence[str], None] = 'fa8b6af0774b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photos', 'collections', ['collection_id'], ['id'])
    op.drop_index(op.f('ix_studio_settings_email'), table_name='studio_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_studio_settings_email'), 'studio_settings', ['email_id'], unique=True)
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'collection_id')
    # ### end Alembic commands ###
